[workspace]
resolver = "2"
members = ["src/01-minimal"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
# Allows defmt to display log locations even in release
debug = true
panic = "abort"

[profile.dev]
panic = "abort"
