name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Check compilation
        run: |
          cargo check --target thumbv7em-none-eabihf
          for dir in src/*; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Checking $dir..."
              cargo check --manifest-path="$dir/Cargo.toml" --target thumbv7em-none-eabihf
            fi
          done

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - name: Build
        run: |
          cargo build --target thumbv7em-none-eabihf
          for dir in src/*; do
            if [ -f "$dir/Cargo.toml" ]; then
              echo "Building $dir..."
              cargo build --manifest-path="$dir/Cargo.toml" --target thumbv7em-none-eabihf
            fi
          done
